### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by GeeWee** [GeeWee/kommunevalg-kort#2]
# TODO (next steps)

- [ ] Continuous deployment to somewhere where we can cache the Google Sheets values.
- [ ] Figure out and test squarespace integration
- [x] Ensure we don't have any XSS vulnerabillities
- [x] Take into account latest feedback mail
- [x] Add global events to each kommune-list
- [x] Better empty states for e.g. groups and events.
- [x] Add "global" events in sheets
- [x] Create a "main" page with "global" events and events that are close.
- [x] Go through "Todos" in code.
- [x] Make the links work.

# TODO (Styling)
- [x] Style it.
- [x] Style "global" events inside a kommune.
- [x] Make it work on mobile
- [x] Make it look nice inside an iframe
- [x] Figure out how to deal with the iframes height/width restrictions.

# TODO nice to have
- [ ] Analytics and error handling
- [ ] Make a working map where you can pick a kommune
- [x] Page title, favicon etc.
- [ ] Show Events in nabokommuner if there are no events in your kommune.
- [x] Better empty state

# DONE
- [x] Display lists of events and groups per kommune
- [x] Reading from google sheets
- [x] Danish date rendering
